# Generated by Django 5.1.7 on 2025-03-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('institute', 'institute'), ('department', 'department'), ('faculty', 'faculty'), ('student', 'student')], max_length=30, null=True),
        ),
    ]
