# Generated by Django 5.1.7 on 2025-03-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='year_name',
        ),
    ]
