# Generated by Django 5.1.7 on 2025-03-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_year_year_year_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
