# Generated by Django 5.1.7 on 2025-03-14 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student'),
        ('department', '0005_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='faculty',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
            preserve_default=False,
        ),
    ]
